= Hexagonal architecture in enterprise applications
:toc: left
:icons: font
:sectnums:

== Preface

The goal of this document is to propose a generic model of enterprise application architecture. There are a few principles that the model should fulfil:

Zero dependency:: Architecture avoids tight coupling with technical libraries and frameworks.
Dependencies under control:: The maintenance efforts scales well with the application size, i.e. there are no combinatorial effects on changes in this architecture and in the code itself.
Self describing:: So-called _screaming architecture_ -- that is by a folder and source file structure it becomes apparent what purpose the application serves and where to find existing or create new code artefacts.

== Abstraction layers

The model foresees at least three abstraction layers:

Domain:: Contains code artefacts solely connected with business domain.
Application:: Contains code artefacts connected with application logic.
Infrastructure:: Contains code artefacts that realize concrete technical solutions such as web applications, batch processes, event processors, storage implementations, etc.

The only *absolute rule* that each code artifact belonging to that model must fulfil is related to the dependencies with other code artifact: the dependency must always point inward which means that any "inner" artifact cannot depend on any "outer" artifact. It is better visualized on the next figure.

[ditaa, "hexagonal-architecture"]
....
    /------------------------------\
    |                              |
    |                              |
    |    /--------------------\    |
    |    |                    |    |
    |    |                 <---=-  |
    |    |    /----------\    |    |
    |  -=-->  |          |    |    |
    |    |  -=-->      <--=-  |    |
    |    |    |  domain  |    |    |
    |    |    \----------/    |    |
    |    |                    |  <---=-
    |    |     application    |    |
    |    \--------------------/    |
    |                              |
    |        infrastructure        |
    \------------------------------/
....

The second rule which is less strict is that most of technical dependencies (such as frameworks, concrete MVC libraries, Spring, JPA etc) are allowed for artifacts located in *infrastructure* layer -- this is why it is called "infrastructure".

Why this rule is less strict? Because it is still necessary and possible to add _some_ technical dependencies to the domain layer:

* if you program in Java, you surely depend on Java Standard Library,
* if you model your domain objects as immutables, you may want to use _vavr_ as a library,
* if you model your domain in reactive style, you may want to use _project reactor_ as a dependency.

There is a big rule of thumb here, whether the dependency is ok or not. For each of mentioned examples you can of course develop an abstraction but this may be considered as "not so pragmatic" approach. I personally ask myself a question: is this library implementing certain technical protocol (thus it should be hidden behind a port) or is this just an extension to the programming language I use (then maybe such dependency is still ok for my domain).

=== Why domain and application are separated?

In ideal world domain depicts a core business logic that is the essence of the business that we try to digitize with our project. Our goal always should be to make it as close to the way the real world works as possible. In result, all artifacts that belongs to the _domain_ should be well understood also for non-technical stuff, including business analysts and product owners. If you need to add here any logic that may be application-specific thus a bit cryptic for such people, it may be a good idea to keep it separate - therefore in the application layer.

Indeed, it is reasonable to place all cross-cutting concepts such as transaction handling, access control to application layer as well. Application components and facades (that are different and more specific than business components) are also items that fits _application_ layer well.

Such separation is exceptionally well suited for microservice projects:

[ditaa, "microservice-layout"]
....
/----------------------------------------------------------\
|domain                                                    |
|     +-=----------+--------------+------------+           |
|     |            |              |            |           |
|     V            |              |            |           |
|  +------+     +--+--------+ +---+-------+ +--+--------+  |
|  |shared|     |subdomain 1| |subdomain 2| |subdomain 3|  |
|  +------+     +-----------+ +-----------+ +-----------+  |
|                    ^             ^            ^   ^      |
\--------------------|-------------|------------|---|------/
                     |             +------------+   |
        +------------+             |                |
        :            |             :                :
/-------|------------|-------------|----------------|------\
|       |            |             |                |      |
|  +----+----+   +---+-----+   +---+-----+   +------+--+   |
|  |service 1|   |service 2|   |service 3|   |service 4|   |
|  +---------+   +---------+   +---------+   +---------+   |
|                                                          |
|application                                               |
\----------------------------------------------------------/
....


=== Can we have fewer layers?

Of course, we can. The absolute minimum is split into business logic (usually dubbed as _domain_) and infrastructure. In this case we would usually like to merge _a domain_ and _an application_ together.

[ditaa, "hexagonal-architecture-simplified"]
....
    /------------------------------\
    |                              |
    |                              |
    |    /--------------------\    |
    |    |                    |    |
    |    |                 <---=-  |
    |  -=-->                  |    |
    |    |       domain       |    |
    |    |                    |  <---=-
    |    |                    |    |
    |    \--------------------/    |
    |                              |
    |        infrastructure        |
    \------------------------------/
....


//== Ideas to investigate
//
//=== Dynamic system instabilities
//
//Ripple effect is generated by dynamic system instability, as depicted on following diagram.
//
//[ditaa,"system-with-feedback"]
//....
//   x   +------------+
//------>|            |   y
//       |   system   +----+-->
//   +-->|            |    |
//   |   +------------+    |
//   |                     |
//   +---------------------+
//....
