@startuml
package "domain.itemclasses" #lightgrey {
    class Category {
       +name: String,
       +description: String
    }

    Category "*" --- "0..1" Category: parent

    class ItemClass {
        +name: String
        +description: String
    }

    class ItemClassVersion {
        +version: Int
    }

    ItemClass "*" --- "*" Category: belongs
    ItemClassVersion "1" ---> "1" ItemClass: itemClass

    class Attribute {
        +name: String
    }
    abstract class AttributeType
    class ScalarType
    class DictionaryType
    class DictionaryItem {
        +value: String
    }

    class Unit {
        +name: String
        +code: String
    }

    AttributeType <|-- ScalarType
    AttributeType <|-- DictionaryType
    ScalarType o-- "1" Unit: unit
    DictionaryType *-- "*" DictionaryItem: items

    Attribute o-- "1" AttributeType: type

    ItemClass o-- "*" Attribute: attributes
}
package "domain.items" #lightblue {
    class Item
    abstract class Value
    class ScalarValue {
        value: Double
    }
    class DictionaryValue {
        value: String
    }

    Value <|-- ScalarValue
    Value <|-- DictionaryValue
    Item "*" --> "1" ItemClassVersion
    Value "*" --* "1" Item: valuation
    Value "*" --> "1" Attribute: of
}
@enduml