@startuml
package domain #BUSINESS {
    [component1]
    [component2]
    [component3]
}
package app #MediumTurquoise {
    [app component 1]
    [app component 2]
}
package infra #SkyBlue {
    [JDBI store]
    [JPA store]
    [Spring Web]
}

app .left.> domain
infra .left.> app
infra ..> domain
@enduml