@startuml
left to right direction
:Data Provisioner: as Provisioner
package Import {
    (Import units) as (ImportUnits)
    (Import categories) as (ImportCategories)
    (Import item classes) as (ImportItemClasses)
}

Provisioner -> (ImportUnits)
Provisioner -> (ImportItemClasses)
Provisioner -> (ImportCategories)

@enduml