@startuml

[Springboot] as springboot
[jdbi]
[jackson]

package "Domain" #lightyellow {
    [items]
    [inventory]
        inventory ...> items
    [production]
        production ...> items
        production ...> inventory
}


package "Adapters" #lightblue {
    [store/jdbi] as store_jdbi
        store_jdbi ...> items
        store_jdbi ...> inventory
        store_jdbi ...> production
        store_jdbi ...> jdbi

    [web/spring] as web_spring
        web_spring ...> items
        web_spring ...> inventory
        web_spring ...> production
        web_spring ...> store_jdbi
        web_spring ...> springboot
        web_spring ...> jackson
        web_spring ...> jdbi
}


@enduml